version: "3"

services:
  fastapi:
    build: .
    networks:
      - net_test
    ports:
      - "8000:8000"
    container_name: 'fastApi_test'
    restart: always
    volumes:
      - .:/app:delegated
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    networks:
      - net_test
    ports:
      - "5432:5432"
    container_name: 'postgres_test'
    restart: always
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_SERVER=postgres:5432

volumes:
  postgres_db: { name: postgres_db }

networks:
  net_test:
    driver: bridge
