version: "3"

services:
  fastapi:
    build: .
    networks:
      - net_test
    ports:
      - "8000:8000"
    container_name: 'fastApi_test'
    restart: always
    volumes:
      - .:/app
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    networks:
      - net_test
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass

  mongo-express:
    image: mongo-express
    restart: always
    networks:
      - net_test
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://user:pass@mongo:27017/

volumes:
  mongo_db: { name: mongo_db }

networks:
  net_test:
    driver: bridge
