version: "3"

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    container_name: 'fastApi_test'
    restart: always

# subir um nginx como balanceador de carga
#  nginx:
#    image: nginx:latest
#    ports:
#      - "80:80"
#    container_name: 'nginx_test'
#    restart: always
#    depends_on:
#      - fastapi
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf

# subir um postgres como banco de dados
#  postgres:
#    image: postgres:latest
#    ports:
#      - "5432:5432"
#    container_name: 'postgres_test'
#    restart: always
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_DB=postgres
#    volumes:
#      - ./postgres_data:/var/lib/postgresql/data
