name: Python test action

on:
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - name: Fetch project code
        uses: actions/checkout@v2
  
      - name: Set up Python 3.11.4
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run Flake8
        run: poetry run flake8 .

      - name: Run test
        run: poetry run task test

      - name: Generate report
        run: poetry run task report-md
        if: always()

      - name: Commet Report PR
        uses: thollander/actions-comment-pull-request@v2
        if: always()
        with:
          filePath: ./report.md
