name: Python test action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11.4
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run Flake8
        run: poetry run flake8 .

      - name: Run test
        run: poetry run task test

  report_and_comment:
    runs-on: ubuntu-latest
    needs: tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.11.4
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Generate report
        run: poetry run task report-md

      - name: Comment Report on PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: ./report.md
          GITHUB_TOKEN: ${{ secrets.COMMET_PR_GITHUB_TOKEN }}